POST http://localhost:5000/api/parkOfficers HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

{
    "fullName":"Sdio Qwint",
    "badgeNumber":"FIO123",
    "district":"LosAngeles,Opresor"
}